### ISSUE TITLE
pretrained weight of ScaffNet on 0.05% density

### ISSUE THREAD

**Issue by zinuok** [alexklwong/learning-topology-synthetic-data#1]
Hello, thank you for sharing your nice works.

It seems that you've also conducted on VOID 0.05% density dataset in arxiv paper.
However, the provided pre-trained weight of ScaffNet was trained on SceneNet 0.50% density, is it right?
If you get a chance, (and if the file still exists) could you upload the ScaffNet's pre-trained weight on 0.05% density in SceneNet?

Best regards,
Jinwoo Jeon

**Comment by zinuok** [comment]
Never mind ! 
It seems like a request that annoys you too much.. 
I will train myself :)
thank you again !

**Comment by alexklwong** [comment]
Hi Jinwoo,

Just to be clear, the experiments on sensitivity to input density were tested on 0.50%, 0.15%, and 0.05%, but the model itself was trained on 0.50%. This is to gauge how sensitive the model is if one were to change its input in a real world setting. If one were to train on 0.05% and test on it as well then the task is easy. I recall getting some 50-60 MAE I believe, approximately as good as other experiments where the input was much denser, which realistically shouldn’t happen.
